name: CMake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.11
        environment-file: environment.yml
        auto-activate-base: false

    - name: Build and Test
      run: |
        mkdir -p build
        cd ./build
        conda activate word_advisor_lib_env_01
        cmake ..
        make
        ./output
        cp -vr ../test.py .
        python3.11 ./test.py

